# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ce6e22660e9d4946ad11cd36e26fac13b1eb757ec74295fdb4a0384a5e5f425823bfa33a90de4ff49ebc78403f96dcb584552c012a627c6b68984b7f802b03

test:
  secret_key_base: ff3e2964ea55c130392f501d89a67c7cbfc44683359d4221ad63a6aeef3163b0318b82e39cdb3bc3800c666369dce0444bce5595c961be41ca31bc58b30e258d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
